Update fastapi to the latest version
digitalliving/openapi-to-fastapi pull request #15
Opened 2021-09-02 11:50 UTC by omarudolley

Update openapi-to-fastapi to work with latest version of FastAPI.

2021-09-02 12:01 UTC, joakimnordling commented on pyproject.toml
> +pre-commit = "^2.14.1"
Pre-commit should not be added as a dependency.

2021-09-02 12:03 UTC, joakimnordling requested changes
Please ensure there's no huge differences in the whitespace (feel free to add pre-commit hook for ensuring that).

Please don't add pre-commit as a dependency.

2021-09-03 12:16 UTC, joakimnordling approved these changes
LGTM

2021-09-06 08:55 UTC, fbjorn approved these changes

2021-09-06 08:59 UTC, merged